version: '3.2'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=twitter
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d twitter"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  client:
    build:
      context: ./client  # Контекст сборки - папка client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - my_network
    depends_on:
      - server

networks:
  my_network:
    driver: bridge
